portfolioapp/urls.py
from django.urls import path

from portfolioapp.views import HomeView, DiscoverArtistsView, DiscoverPhotosView, PortfolioDetailView, \
    AddPhotoView, EditPhotoView, DeletePhotoView, PortfolioPhotoDetailView, CategoryView, \
    CategoryPhotoDetailView, UpdatePortfolioView, LikePhotoView, DislikePhotoView, DiscoverPhotoDetailView, \
    AddCommentView, RemoveCommentView, SearchPhotosView, SearchArtistsView, SearchPhotoDetailView

#regarding home and discover page
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('discover/photos/', DiscoverPhotosView.as_view(), name='discover-photos'),
    path('discover/artists/', DiscoverArtistsView.as_view(), name='discover-artists'),
    path('discover/photos/photo/<int:pk>', DiscoverPhotoDetailView.as_view(), name='discover-photo-detail'),
    path('discover/photos/search/', SearchPhotosView, name='search-photos'),
    path('discover/photos/<str:searched>/<int:pk>', SearchPhotoDetailView, name='search-result-photo-detail'),
    path('discover/artists/search/', SearchArtistsView, name='search-artists'),
]

#regarding portfolio page
urlpatterns+=[
    path('portfolio/<int:pk>', PortfolioDetailView.as_view(), name='portfolio-detail'),
    path('portfolio/photo/<int:pk>', PortfolioPhotoDetailView.as_view(), name='portfolio-photo-detail'),
    path('portfolio/update/<int:pk>', UpdatePortfolioView.as_view(), name='portfolio-update'),
]

#regarding category pages
urlpatterns+=[
    path('category/<str:cat>', CategoryView, name='category-detail'),
    path('category/<str:cat>/photo/<int:pk>', CategoryPhotoDetailView, name='category-photo-detail'),
]

#regarding photo create, update, delete
urlpatterns+=[
    path('add_photo/', AddPhotoView.as_view(), name='add-photo'),
    path('photo/edit_photo/<int:pk>', EditPhotoView.as_view(), name='edit-photo'),
    path('photo/delete_photo/<int:pk>', DeletePhotoView.as_view(), name='delete-photo'),
]

#regardin likes and comments
urlpatterns+=[
    path('like/<int:pk>', LikePhotoView, name='like-photo'),
    path('dislike/<int:pk>', DislikePhotoView, name='dislike-photo'),
    path('comment/<int:pk>', AddCommentView, name='add-comment'),
    path('comment/delete/<int:pk>/<int:com_id>', RemoveCommentView, name='remove-comment'),
]

portfolioapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import ImageField, CharField, ForeignKey, BooleanField, TextField, OneToOneField, DateTimeField
from django.urls import reverse


class Portfolio(models.Model):
    photographer = OneToOneField(User, on_delete=models.CASCADE)
    cover_image = ImageField(upload_to='images/cover_images/', default='defaults/default-cover-pic.jpg')
    profile_pic = ImageField(upload_to='images/profile_pics', default='defaults/default_profile_pic.jpg')
    location = CharField(max_length=50, blank=True, null=True, default='Planet Earth')  # country or city of origin
    artistic_name = CharField(max_length=50,default='My photography portfolio') #for photographers who present themselves with artistic names
    bio = TextField(null=True,blank=True,default='My bio') #photographer's biography

    def __str__(self):
        return self.artistic_name + ' | ' + self.photographer.__str__()

    def get_absolute_url(self):
        return reverse('portfolio-detail', args=[str(self.id)])


class Category(models.Model):
    name = CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('discover-photos')


class Photo(models.Model):
    light = [
        ('Natural light', 'Natural light'),
        ('Studio light', 'Studio light'),
        ('Mixed light', 'Mixed light')
    ]

    image = ImageField(upload_to='images/')
    upload_date = DateTimeField(auto_now_add=True)
    portfolio = ForeignKey(Portfolio, on_delete=models.CASCADE)
    category = CharField(max_length=50)

    title = CharField(max_length=50, blank=False, null=False)
    description = CharField(max_length=150, blank=True)

    camera_name = CharField(max_length=100, default='unknown',blank=True)
    lens = CharField(max_length=100, default='unknown',blank=True)
    used_light = CharField(max_length=50, choices=light, default='Natural light')

    class Meta:
        ordering = ['-upload_date']

    def __str__(self):
        return self.title + " | " + str(self.portfolio.photographer) + " | " + str(self.upload_date)

    def get_absolute_url(self):
        return reverse('portfolio-photo-detail', args=[str(self.id)])


class Like(models.Model):
    user = ForeignKey(User, on_delete=models.CASCADE)
    photo = ForeignKey(Photo, on_delete=models.CASCADE)
    created_on = DateTimeField(auto_now_add=True)


class Comment(models.Model):
    author = ForeignKey(User, on_delete=models.CASCADE)
    photo = ForeignKey(Photo, on_delete=models.CASCADE)
    body = TextField()
    created_on = DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']




templates/add-photo.html
{% extends 'base.html' %}
{% load static %}


{% block additional_links %}
{% endblock %}


{% block content %}
    {% if user.is_authenticated %}
        <div class="container h-100 ">
            <h1 class="text-center text-light p-5" style="font-weight: bold">Add Photo to Portfolio:</h1>
            <div class=" row justify-content-center mb-5">
                <div class="col-7 border border-light rounded" style="background-color: #1a1a1a">
                    <form method="POST" enctype="multipart/form-data" class="text-light p-4">
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                            <div class="form-group mb-3">
                                <label class="mb-2" for="{{field.auto_id}}" style="font-size: 20px">
                                    <i class="bi bi-dot text-success"></i>
                                    {{ field.label }}
                                </label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        {% for field in form.hidden_fields %}
                            {{ field }}
                        {% endfor %}
                        <div class="form-group text-center">
                            <button  class="btn btn-success btn-lg me-4" type="submit">Save</button>
                            <a href="{% url 'home' %}" class="btn btn-danger btn-lg ms-4">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <script>
            document.getElementById("portfolio").value = "{{ user.portfolio.id }}";
        </script>
    {% else %}
        <div class="container h-100 ">
            <h1 class="text-center text-light p-5" style="font-weight: bold">Content not available!</h1>
            <div class=" row justify-content-center  text-center mb-5">
                <div class="col-7 border border-light rounded text center" style="background-color: #1a1a1a">
                    <h3 class="p-3 text-danger">You have to be logged in to see this content</h3>
                    <a href="{% url 'login' %}" class="btn btn-lg btn-success mb-4">Log in</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/category-photo-detail.html
{% extends 'base.html' %}
{% load static %}

{% block additional_links %}
    <link rel="stylesheet" href="{% static 'css/photo-detail.css' %}">
{% endblock %}

{% block content %}

    <div class="container-fluid" style="background-color: #282828;height: 70vh;">
        <div class="row justify-content-center">
            <div class="col-md-1 my-auto text-center">
                {% if photo.category == prev_ph.category %}
                    <a href="{% url 'category-photo-detail' category prev_ph.pk %}" class="text-decoration-none">
                        <i class="bi bi-chevron-double-left text-light" style="font-size: 40px"></i>
                    </a>
                {% else %}
                    <i class="bi bi-chevron-double-left text-muted" style="font-size: 40px"></i>
                {% endif %}
            </div>

            <div class="col-md-10" style="height: 70vh;">
                <div class="pic justify-content-center text-center">
                    <img class="mx-auto" src="{{ photo.image.url }}">
                </div>
            </div>
            <div class="col-md-1 my-auto text-center">
                {% if photo.category == next_ph.category %}
                    <a href="{% url 'category-photo-detail' category next_ph.pk %}" class="text-decoration-none">
                        <i class="bi bi-chevron-double-right text-light" style="font-size: 40px"></i>
                    </a>
                {% else %}
                        <i class="bi bi-chevron-double-right text-muted" style="font-size: 40px"></i>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-5 mt-3 mb-3 ms-3 me-3 rounded-3" style="background-color: #282828">
                <div class="profile-pic ms-3 p-3 float-start">
                    <img src="{{photo.portfolio.profile_pic.url}}">
                </div>
                <div class="text-left mt-3">
                    <h2 class="text-light text-left" style="">{{ photo.title }}</h2>
                    <h6 class="text-muted text-left" style="font-style: italic">
                        Published by
                        <a class="text-info text-decoration-none" href="{% url 'portfolio-detail' photo.portfolio.pk%}">
                            {{ photo.portfolio.photographer.username }}
                        </a>
                        on {{ photo.upload_date|date:"M d, Y" }} in
                        <a class="text-info text-decoration-none" href="{% url 'category-detail' photo.category %}">
                            {{ photo.category.lower }}
                        </a> category.
                    </h6>
                    {% if user.is_authenticated and user.id == photo.portfolio.photographer.id or not user.is_authenticated %}
                        <h5 class="text-light">
                            <i class="bi bi-heart-fill text-info"></i> {{ photo.like_set.count }}
                        </h5>
                    {% elif user.is_authenticated %}
                        {% if user.id != photo.portfolio.photographer.id %}
                            {% if liked %}
                                <form method="POST" action="{% url 'dislike-photo' photo.pk %}" id="flike">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.path }}">
                                    <a href="#" onclick="document.getElementById('flike').submit();"
                                       class="text-decoration-none">
                                        <h5 class="text-light">
                                            <i class="bi bi-heart-fill text-info"></i> {{ photo.like_set.count }}
                                        </h5>
                                    </a>
                                </form>
                            {% elif not liked %}
                                <form method="POST" action="{% url 'like-photo' photo.pk %}" id="fdislike">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.path }}">
                                    <a href="#" onclick="document.getElementById('fdislike').submit();"
                                       class="text-decoration-none">
                                        <h5 class="text-light">
                                            <i class="bi bi-heart text-info"></i> {{ photo.like_set.count }}
                                        </h5>
                                    </a>
                                </form>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                    <hr>
                </div>
                <h3 class="text-light text-center mt-3 ms-2" style="font-family: 'Kaushan Script', cursive">Photo details:</h3>
                <div class="text-light ms-2 me-2 mb-3 border border-light">
                    <p class="mt-3" style="font-size: 20px">
                        <i class="bi bi-dot text-light"></i>
                        Photo description:
                    </p>
                    <p class="mb-3 ms-4 me-4">{{ photo.description }}</p>
                    <p style="font-size: 20px">
                        <i class="bi bi-dot text-light"></i>
                        Gear:
                    </p>
                    <p class="mb-3 ms-4">
                        <i class="bi bi-camera-fill text-light"></i>
                        Camera: {{ photo.camera_name }}
                    </p>
                    <p class="mb-3 ms-4">
                        <i class="bi bi-disc text-light"></i>
                        Lens: {{ photo.lens }}
                    </p>
                    <p class="mb-3 ms-4">
                        <i class="bi bi-brightness-high-fill text-light"></i>
                        Light: {{ photo.used_light }}
                    </p>
                </div>
                {% if user.is_authenticated %}
                    {% if user.id == photo.portfolio.photographer.id %}
                        <div class="text-center p-2 mb-3">
                            <a href="{% url 'edit-photo' photo.pk %}" class="btn btn-info btn-sm">Edit photo</a>
                            <a href="{% url 'delete-photo' photo.pk %}" class="btn btn-danger btn-sm">Delete
                                photo</a>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-5 mt-3 mb-3 ms-3 me-3 rounded-3" style="background-color: #282828">
                <h2 class="text-light text-center mt-4 mb-3" style="font-family: 'Kaushan Script', cursive">Comments</h2>
                <hr>
                {% if photo.comment_set.all  %}
                    <div {% if not user.is_authenticated %}class="text-light ms-3 me-3 mb-3 border border-info overflow-auto h-75"
                         {% else %} class="text-light ms-3 me-3 mb-3 border border-info overflow-auto" style="height: 240px"{% endif %}>
                         <div class="p-2">
                            {% for comment in photo.comment_set.all %}
                                <h6 class="text-light text-left ms-2 mt-2">
                                    {{ comment.author.first_name }} {{ comment.author.last_name }} (
                                    <a class="text-info text-decoration-none" href="{% url 'portfolio-detail' photo.portfolio.pk %}">
                                        @{{ comment.author.username }}
                                    </a>), commented on {{ comment.created_on }}
                                    {% if user.is_authenticated and user.id == comment.author.id %}
                                        <form method="POST" action="{% url 'remove-comment' photo.pk comment.id %}" id="comform">
                                            {% csrf_token %}
                                            <input type="hidden" name="goto" value="{{ request.path }}">
                                            <a href="#" onclick="document.getElementById('comform').submit();"
                                                class="text-danger text-decoration-none mt-2">
                                            (Delete)
                                            </a>
                                        </form>
                                    {% endif %}
                                </h6>
                                <h6 class="text-left text-light ms-2  mb-3" style="font-style: italic">
                                    {{ comment.body }}
                                </h6>
                                <hr style="width: 98% !important;">
                            {% endfor %}
                         </div>
                    </div>
                {% else %}
                    <div {% if not user.is_authenticated %}class="text-light text-center ms-3 me-3 mb-3 border border-info overflow-auto h-75"
                         {% else %} class="text-light text-center ms-3 me-3 mb-3 border border-info overflow-auto" style="height: 240px"{% endif %}>
                        <h3 class="mt-5 text-danger">This photo has no comments yet.</h3>
                    </div>
                {% endif %}

                {% if user.is_authenticated %}
                    <form method="POST" action="{% url 'add-comment' photo.pk %}" class="text-light ps-4 pe-4 pb-4 pt-2 mt-auto">
                        {% csrf_token %}
                        {% for field in comment_form.visible_fields %}
                            <div class="form-group mb-3">
                                <label class="mb-2" for="{{field.auto_id}}" style="font-size: 20px">
                                    <h4></h4>{{ field.label }}
                                </label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        {% for field in comment_form.hidden_fields %}
                            {{ field }}
                        {% endfor %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <div class="form-group text-center">
                            <button  class="btn btn-info btn-sm me-4" type="submit">Post</button>
                        </div>
                    </form>
                {% endif %}

                <script>
                    document.getElementById("photo").value = "{{ photo.id }}";
                    document.getElementById("author").value = "{{ user.id }}";
                </script>
            </div>
        </div>
    </div>

{% endblock %}

templates/discover-searched-photo-detail.html
{% extends 'base.html' %}
{% load static %}

{% block additional_links %}
    <link rel="stylesheet" href="{% static 'css/photo-detail.css' %}">
{% endblock %}

{% block content %}

    <div class="container-fluid" style="background-color: #282828;height: 70vh;">
        <div class="row justify-content-center">
            <div class="col-md-1 my-auto text-center">
                {% if prev_ph in qs.all %}
                    <a href="{% url 'search-result-photo-detail' searched prev_ph.pk %}" class="text-decoration-none">
                        <i class="bi bi-chevron-double-left text-light" style="font-size: 40px"></i>
                    </a>
                {% else %}
                    <i class="bi bi-chevron-double-left text-muted" style="font-size: 40px"></i>
                {% endif %}
            </div>

            <div class="col-md-10" style="height: 70vh;">
                <div class="pic justify-content-center text-center">
                    <img class="mx-auto" src="{{ photo.image.url }}">
                </div>
            </div>
            <div class="col-md-1 my-auto text-center">
                {% if next_ph in qs.all %}
                    <a href="{% url 'search-result-photo-detail' searched next_ph.pk %}" class="text-decoration-none">
                        <i class="bi bi-chevron-double-right text-light" style="font-size: 40px"></i>
                    </a>
                {% else %}
                        <i class="bi bi-chevron-double-right text-muted" style="font-size: 40px"></i>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-5 mt-3 mb-3 ms-3 me-3 rounded-3" style="background-color: #282828">
                <div class="profile-pic ms-3 p-3 float-start">
                    <img src="{{photo.portfolio.profile_pic.url}}">
                </div>
                <div class="text-left mt-3">
                    <h2 class="text-light text-left" style="">{{ photo.title }}</h2>
                    <h6 class="text-muted text-left" style="font-style: italic">
                        Published by
                        <a class="text-info text-decoration-none" href="{% url 'portfolio-detail' photo.portfolio.pk%}">
                            {{ photo.portfolio.photographer.username }}
                        </a>
                        on {{ photo.upload_date|date:"M d, Y" }} in
                        <a class="text-info text-decoration-none" href="{% url 'category-detail' photo.category %}">
                            {{ photo.category.lower }}
                        </a> category.
                    </h6>
                    {% if user.is_authenticated and user.id == photo.portfolio.photographer.id or not user.is_authenticated %}
                        <h5 class="text-light">
                            <i class="bi bi-heart-fill text-info"></i> {{ photo.like_set.count }}
                        </h5>
                    {% elif user.is_authenticated %}
                        {% if user.id != photo.portfolio.photographer.id %}
                            {% if liked %}
                                <form method="POST" action="{% url 'dislike-photo' photo.pk %}" id="flike">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.path }}">
                                    <a href="#" onclick="document.getElementById('flike').submit();"
                                       class="text-decoration-none">
                                        <h5 class="text-light">
                                            <i class="bi bi-heart-fill text-info"></i> {{ photo.like_set.count }}
                                        </h5>
                                    </a>
                                </form>
                            {% elif not liked %}
                                <form method="POST" action="{% url 'like-photo' photo.pk %}" id="fdislike">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.path }}">
                                    <a href="#" onclick="document.getElementById('fdislike').submit();"
                                       class="text-decoration-none">
                                        <h5 class="text-light">
                                            <i class="bi bi-heart text-info"></i> {{ photo.like_set.count }}
                                        </h5>
                                    </a>
                                </form>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                    <hr>
                </div>
                <h3 class="text-light text-center mt-3 ms-2" style="font-family: 'Kaushan Script', cursive">Photo details:</h3>
                <div class="text-light ms-2 me-2 mb-3 border border-light">
                    <p class="mt-3" style="font-size: 20px">
                        <i class="bi bi-dot text-light"></i>
                        Photo description:
                    </p>
                    <p class="mb-3 ms-4 me-4">{{ photo.description }}</p>
                    <p style="font-size: 20px">
                        <i class="bi bi-dot text-light"></i>
                        Gear:
                    </p>
                    <p class="mb-3 ms-4">
                        <i class="bi bi-camera-fill text-light"></i>
                        Camera: {{ photo.camera_name }}
                    </p>
                    <p class="mb-3 ms-4">
                        <i class="bi bi-disc text-light"></i>
                        Lens: {{ photo.lens }}
                    </p>
                    <p class="mb-3 ms-4">
                        <i class="bi bi-brightness-high-fill text-light"></i>
                        Light: {{ photo.used_light }}
                    </p>
                </div>
                {% if user.is_authenticated %}
                    {% if user.id == photo.portfolio.photographer.id %}
                        <div class="text-center p-2 mb-3">
                            <a href="{% url 'edit-photo' photo.pk %}" class="btn btn-info btn-sm">Edit photo</a>
                            <a href="{% url 'delete-photo' photo.pk %}" class="btn btn-danger btn-sm">Delete
                                photo</a>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-5 mt-3 mb-3 ms-3 me-3 rounded-3" style="background-color: #282828">
                <h2 class="text-light text-center mt-4 mb-3" style="font-family: 'Kaushan Script', cursive">Comments</h2>
                <hr>
                {% if photo.comment_set.all  %}
                    <div {% if not user.is_authenticated %}class="text-light ms-3 me-3 mb-3 border border-info overflow-auto h-75"
                         {% else %} class="text-light ms-3 me-3 mb-3 border border-info overflow-auto" style="height: 240px"{% endif %}>
                         <div class="p-2">
                            {% for comment in photo.comment_set.all %}
                                <h6 class="text-light text-left ms-2 mt-2">
                                    {{ comment.author.first_name }} {{ comment.author.last_name }} (
                                    <a class="text-info text-decoration-none" href="{% url 'portfolio-detail' photo.portfolio.pk %}">
                                        @{{ comment.author.username }}
                                    </a>), commented on {{ comment.created_on }}
                                    {% if user.is_authenticated and user.id == comment.author.id %}
                                        <form method="POST" action="{% url 'remove-comment' photo.pk comment.id %}" id="comform">
                                            {% csrf_token %}
                                            <input type="hidden" name="goto" value="{{ request.path }}">
                                            <a href="#" onclick="document.getElementById('comform').submit();"
                                                class="text-danger text-decoration-none mt-2">
                                            (Delete)
                                            </a>
                                        </form>
                                    {% endif %}
                                </h6>
                                <h6 class="text-left text-light ms-2  mb-3" style="font-style: italic">
                                    {{ comment.body }}
                                </h6>
                                <hr style="width: 98% !important;">
                            {% endfor %}
                         </div>
                    </div>
                {% else %}
                    <div {% if not user.is_authenticated %}class="text-light text-center ms-3 me-3 mb-3 border border-info overflow-auto h-75"
                         {% else %} class="text-light text-center ms-3 me-3 mb-3 border border-info overflow-auto" style="height: 240px"{% endif %}>
                        <h3 class="mt-5 text-danger">This photo has no comments yet.</h3>
                    </div>
                {% endif %}

                {% if user.is_authenticated %}
                    <form method="POST" action="{% url 'add-comment' photo.pk %}" class="text-light ps-4 pe-4 pb-4 pt-2 mt-auto">
                        {% csrf_token %}
                        {% for field in comment_form.visible_fields %}
                            <div class="form-group mb-3">
                                <label class="mb-2" for="{{field.auto_id}}" style="font-size: 20px">
                                    <h4></h4>{{ field.label }}
                                </label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        {% for field in comment_form.hidden_fields %}
                            {{ field }}
                        {% endfor %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <div class="form-group text-center">
                            <button  class="btn btn-info btn-sm me-4" type="submit">Post</button>
                        </div>
                    </form>
                {% endif %}

                <script>
                    document.getElementById("photo").value = "{{ photo.id }}";
                    document.getElementById("author").value = "{{ user.id }}";
                </script>
            </div>
        </div>
    </div>

{% endblock %}

templates/portfolio-detail.html
{% extends 'base.html' %}
{% load static %}

{% block additional_links %}
    <link rel="stylesheet" href="{% static 'css/portfolio-detail.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="header-image">
            <img src="{{ portfolio.cover_image.url }}">
        </div>
        <div class="profile-pic">
            <img src="{{ portfolio.profile_pic.url }}">
        </div>
        <div class="profile-info justify-content-center text-center">
            <h2 class="text-light" style="font-family: 'Kaushan Script', cursive">{{ portfolio.artistic_name}}</h2>
            <h6 class="text-muted mt-1" style="font-style: italic">@{{ portfolio.photographer.username }}</h6>
            <div class=" row justify-content-center">
                <div class="col-6">
                    <p class="text-light text-center p-1" style="font-weight: lighter; font-size: 15px">
                        {{ portfolio.bio }}
                    </p>
                </div>
            </div>
            <h5 class="text-light">
                <i class="bi bi-geo-alt text-light"></i>
                {{ portfolio.location }}</h5>
            {% if user.is_authenticated and portfolio.photographer.id == user.id  %}
                <a href="{% url 'portfolio-update' portfolio.pk %}" class="btn btn-info text-center mt-2 mb-2 me-3" style="width: 12%">
                Update portfolio
                </a>
                <a href="{% url 'add-photo' %}" class="btn btn-info text-center mt-2 mb-2 ms-3" style="width: 12%">
                Add photo
                </a>
            {% endif %}
         </div>
        <hr>
    </div>
    <div class="main mt-4 mb-4" style="background-color: #282828">
        <div class="container p-3">
            {% for photo in portfolio.photo_set.all %}
            <div class="img-holder">
               <a href="{% url 'portfolio-photo-detail' photo.pk %}"><img src="{{photo.image.url}}" alt=""></a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}